(function(g){var window=this;var Cqa=function(a,b){return g.Wb(a,b)},u6=function(a,b,c){a.l.set(b,c)},v6=function(a){u6(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},w6=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Zm(a.l,b,c)},Dqa=function(a,b){var c=[];
g.aj(b,function(d){try{var e=g.Jn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.In(e)&&c.push(d):c.push(d)},a);
return c},Eqa=function(a,b){var c=Dqa(a,b);
(0,g.z)(c,function(d){g.Jn.prototype.remove.call(this,d)},a)},x6=function(a){if(a.fd){if(a.fd.locationOverrideToken)return{locationOverrideToken:a.fd.locationOverrideToken};
if(null!=a.fd.latitudeE7&&null!=a.fd.longitudeE7)return{latitudeE7:a.fd.latitudeE7,longitudeE7:a.fd.longitudeE7}}return null},Fqa=function(a,b){g.ab(a,b)||a.push(b)},y6=function(a){var b=0,c;
for(c in a)b++;return b},z6=function(a,b){var c=b instanceof g.zc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},A6=function(){},Gqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Hqa=function(a){if(a.Cd&&"function"==typeof a.Cd)return a.Cd();
if(g.Da(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},Iqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Da(a))(0,g.z)(a,b,void 0);else{if(a.de&&"function"==typeof a.de)var c=a.de();else if(a.Cd&&"function"==typeof a.Cd)c=void 0;else if(g.Ma(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=Hqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Jqa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},B6=function(a,b){g.Ho[a]=!0;
var c=g.Fo();c&&c.publish.apply(c,arguments);g.Ho[a]=!1},C6=function(a){try{var b=(0,g.cy)(),c=(0,g.by)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Kqa=function(){var a=(0,g.by)();
a&&Eqa(a,a.g.kf(!0))},D6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Lqa(this,a.capabilities||""),Mqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Lqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ra(Cqa,Nqa)).forEach(function(c){a.capabilities.add(c)})},Mqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},E6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},F6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},G6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Oqa=function(a){return new E6(a)},H6=function(a){return g.La(a)?(0,g.A)(a,Oqa):[]},I6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},J6=function(a){return g.La(a)?"["+(0,g.A)(a,I6).join(",")+"]":"null"},K6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Pqa=function(a){return(0,g.A)(a,function(b){return{key:b.id,
name:b.name}})},L6=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},M6=function(a,b){return g.Ya(a,function(c){return F6(c,b)})},N6=function(){var a=g.ey("yt-remote-connected-devices")||[];
g.rb(a);return a},Qqa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.A)(a,function(d,e){return 0==e?d:d.substring(c.length)})},O6=function(a){g.dy("yt-remote-connected-devices",a,86400)},Q6=function(){if(P6)return P6;
var a=g.ey("yt-remote-device-id");a||(a=K6(),g.dy("yt-remote-device-id",a,31536E3));for(var b=N6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return P6=d},R6=function(){var a=N6(),b=Q6();
g.ab(a,b);g.gL()&&g.tb(a,b);a=Qqa(a);if(g.bb(a))try{g.yr("remote_sid")}catch(c){}else try{g.xr("remote_sid",a.join(","),-1)}catch(c){}},S6=function(){return g.ey("yt-remote-session-browser-channel")},T6=function(){return g.ey("yt-remote-local-screens")||[]},U6=function(){g.dy("yt-remote-lounge-token-expiration",!0,86400)},Rqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.A)(T6(),function(d){return d.loungeToken}),c=(0,g.A)(a,function(d){return d.loungeToken});
(0,g.$g)(c,function(d){return!g.ab(b,d)})&&U6();
g.dy("yt-remote-local-screens",a,31536E3)},Sqa=function(a,b){g.dy("yt-remote-session-browser-channel",a);
g.dy("yt-remote-session-screen-id",b);var c=N6(),d=Q6();g.ab(c,d)||c.push(d);O6(c);R6()},V6=function(a){a||(C6("yt-remote-session-screen-id"),C6("yt-remote-session-video-id"));
R6();a=N6();g.eb(a,Q6());O6(a)},Tqa=function(){if(!W6){var a=g.Tn();
a&&(W6=new g.Dn(a))}return W6?!!W6.get("yt-remote-use-staging-server"):!1},Uqa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Vqa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X6=function(a){a.length?Wqa(a.shift(),function(){X6(a)}):Y6()},Xqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Wqa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Y6=function(){var a=Vqa();
a&&a(!1,"No cast extension found")},Zqa=function(){if(Yqa){var a=2,b=Vqa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Wqa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y6,c)}},$qa=function(){Zqa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},Z6=function(a,b,c){g.I.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.GC,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},$6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Gqa(a)},a7=function(){},b7=function(){},ara=function(){},cra=function(a){return(a=bra(a))?new ActiveXObject(a):new XMLHttpRequest},bra=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},c7=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ca=new g.hZ(this);this.i=new g.jl;this.i.setInterval(250)},era=function(a,b,c){a.Th=1;
a.Tf=v6(b.clone());a.oh=c;a.u=!0;dra(a,null)},d7=function(a,b,c,d,e){a.Th=1;
a.Tf=v6(b.clone());a.oh=null;a.u=c;e&&(a.yz=!1);dra(a,d)},dra=function(a,b){a.Bi=(0,g.D)();
e7(a);a.Bg=a.Tf.clone();w6(a.Bg,"t",a.A);a.Tk=0;a.wc=a.g.gp(a.g.Fk()?b:null);0<a.Lp&&(a.Fn=new g.ml((0,g.x)(a.xA,a,a.wc),a.Lp));a.ca.da(a.wc,"readystatechange",a.ML);var c=a.Wg?g.dc(a.Wg):{};a.oh?(a.mo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.wc.send(a.Bg,a.mo,a.oh,c)):(a.mo="GET",a.yz&&!g.Od&&(c.Connection="close"),a.wc.send(a.Bg,a.mo,null,c));a.g.ue(1)},hra=function(a,b,c){for(var d=!0;!a.Lg&&a.Tk<c.length;){var e=fra(a,c);
if(e==f7){4==b&&(a.mg=4,g7(15),d=!1);break}else if(e==gra){a.mg=4;g7(16);d=!1;break}else h7(a,e)}4==b&&0==c.length&&(a.mg=1,g7(17),d=!1);a.we=a.we&&d;d||(i7(a),j7(a))},fra=function(a,b){var c=a.Tk,d=b.indexOf("\n",c);
if(-1==d)return f7;c=Number(b.substring(c,d));if(isNaN(c))return gra;d+=1;if(d+c>b.length)return f7;var e=b.substr(d,c);a.Tk=d+c;return e},jra=function(a,b){a.Bi=(0,g.D)();
e7(a);var c=b?window.location.hostname:"";a.Bg=a.Tf.clone();u6(a.Bg,"DOMAIN",c);u6(a.Bg,"t",a.A);try{a.Ae=new ActiveXObject("htmlfile")}catch(n){i7(a);a.mg=7;g7(22);j7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in k7)k=k7[l];else if(l in ira)k=k7[l]=ira[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
k7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.sc("b/12014412"),d+"</body></html>");a.Ae.open();a.Ae.write(g.Nc(c));a.Ae.close();a.Ae.parentWindow.m=(0,g.x)(a.bL,a);a.Ae.parentWindow.d=(0,g.x)(a.Fy,a,!0);a.Ae.parentWindow.rpcClose=(0,g.x)(a.Fy,a,!1);c=a.Ae.createElement("DIV");a.Ae.parentWindow.document.body.appendChild(c);d=g.Dc(a.Bg.toString());d=g.ad(g.Bc(d));d=g.Sc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.ue(1)},e7=function(a){a.Cs=(0,g.D)()+a.o;
kra(a,a.o)},kra=function(a,b){if(null!=a.Ri)throw Error("WatchDog timer not null");
a.Ri=l7((0,g.x)(a.kL,a),b)},m7=function(a){a.Ri&&(g.u.clearTimeout(a.Ri),a.Ri=null)},j7=function(a){a.g.tv()||a.Lg||a.g.xn(a)},i7=function(a){m7(a);
g.Ei(a.Fn);a.Fn=null;a.i.stop();g.jZ(a.ca);if(a.wc){var b=a.wc;a.wc=null;b.abort();b.dispose()}a.Ae&&(a.Ae=null)},h7=function(a,b){try{a.g.zy(a,b),a.g.ue(4)}catch(c){}},mra=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;lra(a,b,function(k){k?c(!0):g.u.setTimeout(function(){mra(a,b,c,d,f)},f)})}},lra=function(a,b,c){var d=new Image;
d.onload=function(){try{n7(d),c(!0)}catch(e){}};
d.onerror=function(){try{n7(d),c(!1)}catch(e){}};
d.onabort=function(){try{n7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{n7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
z6(d,a)},n7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},nra=function(a){this.g=a;
this.i=new a7},ora=function(a){var b=o7(a.g,a.bj,"/mail/images/cleardot.gif");
v6(b);mra(b.toString(),5E3,(0,g.x)(a.LB,a),3,2E3);a.ue(1)},q7=function(a){var b=a.g.F;
if(null!=b)g7(5),b?(g7(11),p7(a.g,a,!1)):(g7(12),p7(a.g,a,!0));else if(a.Gd=new c7(a,void 0,void 0,void 0),a.Gd.Wg=a.Jp,b=a.g,b=o7(b,b.Fk()?a.Ej:null,a.Kp),g7(5),!g.Md||g.od(10))w6(b,"TYPE","xmlhttp"),d7(a.Gd,b,!1,a.Ej,!1);else{w6(b,"TYPE","html");var c=a.Gd;a=!!a.Ej;c.Th=3;c.Tf=v6(b.clone());jra(c,a)}},r7=function(a){g.zk.call(this);
this.headers=new g.Km;this.N=a||null;this.i=!1;this.S=this.g=null;this.aa=this.D="";this.u=0;this.l="";this.o=this.ba=this.C=this.R=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},pra=function(a){return g.Md&&g.nd(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},qra=function(a){return"content-type"==a.toLowerCase()},sra=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;rra(a);s7(a)},rra=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},ura=function(a){if(a.i&&"undefined"!=typeof g.nZ)if(a.S[1]&&4==t7(a)&&2==a.getStatus())u7(a,"Local request error detected and ignored");
else if(a.C&&4==t7(a))g.kl(a.vv,0,a);else if(a.dispatchEvent("readystatechange"),4==t7(a)){u7(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!tra.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<t7(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";rra(a)}}finally{s7(a)}}},s7=function(a,b){if(a.g){vra(a);
var c=a.g,d=a.S[0]?g.Ha:null;a.g=null;a.S=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},vra=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},t7=function(a){return a.g?a.g.readyState:0},v7=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},u7=function(a,b){return b+" ["+a.aa+" "+a.D+" "+a.getStatus()+"]"},w7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new a7;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},wra=function(a,b){this.g=a;
this.map=b;this.context=null},xra=function(a){g.ak.call(this,"statevent",a)},yra=function(a,b){g.ak.call(this,"timingevent",a);
this.size=b},zra=function(a){g.ak.call(this,"serverreachability",a)},Cra=function(a){Ara(a);
if(3==a.g){var b=a.kk++,c=a.Xl.clone();u6(c,"SID",a.l);u6(c,"RID",b);u6(c,"TYPE","terminate");x7(a,c);b=new c7(a,a.l,b,void 0);b.Th=2;b.Tf=v6(c.clone());z6(new Image,b.Tf.toString());b.Bi=(0,g.D)();e7(b)}Bra(a)},Dra=function(a){a.fC(1,0);
a.Xl=o7(a,null,a.Ip);y7(a)},Ara=function(a){a.Zf&&(a.Zf.abort(),a.Zf=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.lf&&(g.u.clearTimeout(a.lf),a.lf=null);z7(a);a.Ad&&(a.Ad.cancel(),a.Ad=null);a.jg&&(g.u.clearTimeout(a.jg),a.jg=null)},Era=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new wra(a.nH++,b));2!=a.g&&3!=a.g||y7(a)},y7=function(a){a.Ad||a.jg||(a.jg=l7((0,g.x)(a.Ey,a),0),a.Mh=0)},Gra=function(a,b){if(1==a.g){if(!b){a.kk=Math.floor(1E5*Math.random());
var c=a.kk++,d=new c7(a,"",c,void 0);d.Wg=null;var e=A7(a),f=a.Xl.clone();u6(f,"RID",c);u6(f,"CVER","1");x7(a,f);era(d,f,e);a.Ad=d;a.g=2}}else 3==a.g&&(b?Fra(a,b):0==a.i.length||a.Ad||Fra(a))},Fra=function(a,b){if(b)if(6<a.Mg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.kk-1;var d=A7(a)}else c=b.C,d=b.oh;else c=a.kk++,d=A7(a);var e=a.Xl.clone();u6(e,"SID",a.l);u6(e,"RID",c);u6(e,"AID",a.hi);x7(a,e);c=new c7(a,a.l,c,a.Mh+1);c.Wg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ad=c;era(c,e,d)},x7=function(a,b){if(a.Tc){var c=a.Tc.Ru();
c&&g.Lb(c,function(d,e){u6(b,e,d)})}},A7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Mg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Mg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Hra=function(a){a.Rb||a.lf||(a.C=1,a.lf=l7((0,g.x)(a.Dy,a),0),a.Gh=0)},B7=function(a){if(a.Rb||a.lf||3<=a.Gh)return!1;
a.C++;a.lf=l7((0,g.x)(a.Dy,a),Ira(a,a.Gh));a.Gh++;return!0},p7=function(a,b,c){a.ko=c;
a.Ee=b.zf;a.A||Dra(a)},z7=function(a){null!=a.Pg&&(g.u.clearTimeout(a.Pg),a.Pg=null)},Ira=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},C7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.tM,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),v6(c));lra(c.toString(),1E4,d)}else g7(2);Jra(a,b)},Jra=function(a,b){a.g=0;
a.Tc&&a.Tc.eu(b);Bra(a);Ara(a)},Bra=function(a){a.g=0;
a.Ee=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Xo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.Xo(b)}},o7=function(a,b,c){var d=g.Vm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=Jqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.oj&&g.Lb(a.oj,function(f,k){u6(d,k,f)});
u6(d,"VER",a.Mg);x7(a,d);return d},l7=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},g7=function(a){D7.dispatchEvent(new xra(D7,a))},Kra=function(){},Lra=function(){this.g=[];
this.i=[]},Mra=function(a,b){this.action=a;
this.params=b||{}},E7=function(a,b){g.I.call(this);
this.g=new g.K(this.SK,0,this);g.J(this,this.g);this.Wc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},F7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Cn;this.i=new E7(this.WL,this);this.g=null;this.ib=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},Nra=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ko,sessionId:a.g.l,arrayId:a.g.hi}},Ora=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Gra(a.g),Cra(a.g));a.D=0},G7=function(a){return!!a.g&&3==a.g.g},Pra=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},H7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.vf(4,a))||"";b&&(this.port=":"+b);this.domain=g.wf(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},I7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ff(c+b,{})},J7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),Td:g.Ra(a.u,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ep(b,a)},Tra=function(){var a=Qra;
Rra();K7.push(a);Sra(K7)},L7=function(a,b){Rra();
var c=K7,d=Ura(a,String(b));g.bb(c)?Vra(d):(Sra(c),(0,g.z)(c,function(e){e(d)}))},Rra=function(){K7||(K7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",K7,void 0))},Vra=function(a){var b=(M7+1)%50;
M7=b;N7[b]=a;O7||(O7=49==b)},Sra=function(a){var b=N7;
if(b[0]){var c=M7,d=O7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
N7=Array(50);M7=-1;O7=!1}},Ura=function(a,b){var c=((0,g.D)()-Wra)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},P7=function(a){g.P.call(this);
this.C=a;this.g=[]},Xra=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Yra=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!L6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Xra(a,b[d])||c;return c},Zra=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},Q7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},S7=function(a){P7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;R7(this);this.info("Initializing with "+J6(this.g))},$ra=function(a){if(a.g.length){var b=(0,g.A)(a.g,function(d){return d.id}),c=I7(a.l,"/pairing/get_lounge_token_batch");
J7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.QC,a),(0,g.x)(a.PC,a))}},R7=function(a){var b=H6(T6());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Yra(a,b)},T7=function(a,b){Rqa((0,g.A)(a.g,G6));
b&&U6()},V7=function(a,b){g.P.call(this);
this.A=b;var c=g.ey("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;U7("Initialized with "+g.Bj(this.g))},asa=function(a,b,c){var d=I7(a.u,"/pairing/get_screen_availability");
J7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},W7=function(a,b){a:if(y6(b)!=y6(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(U7("Updated online screens: "+g.Bj(a.g)),a.g=b,a.O("screenChange"));bsa(a)},X7=function(a){isNaN(a.l)||g.Eo(a.l);
a.l=g.Co((0,g.x)(a.Ir,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},U7=function(a){L7("OnlineScreenService",a)},csa=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},bsa=function(a){a=g.Tb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.dy("yt-remote-online-screen-ids",a.join(","),60):C6("yt-remote-online-screen-ids")},Y7=function(a){P7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};dsa(this)},fsa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Qd();if(k=(c?M6(k,c):null)||M6(k,b)){k.uuid=b;var l=Z7(a,k);asa(a.i,l,function(m){e(m?l:null)})}else c?esa(a,c,(0,g.x)(function(m){var n=Z7(this,new E6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));asa(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},gsa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},esa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ep(I7(a.A,"/pairing/get_lounge_token_batch"),e)},hsa=function(a){a.g=a.l.Qd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+J6(a.g))},dsa=function(a){$7(a);
a.l=new S7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.YC,a));hsa(a);a.o=H6(g.ey("yt-remote-automatic-screen-cache")||[]);$7(a);a.info("Initializing automatic screens: "+J6(a.o));a.i=new V7(a.A,(0,g.x)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.O("onlineScreenChange")},a))},Z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=M6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.dy("yt-remote-automatic-screen-cache",(0,g.A)(a.o,G6)));$7(a);a.u[b.uuid]=b.id;g.dy("yt-remote-device-id-map",a.u,31536E3);return b},$7=function(a){a.u=g.ey("yt-remote-device-id-map")||{}},a8=function(a,b,c){g.P.call(this);
this.S=c;this.F=a;this.i=b;this.l=null},b8=function(a,b){L7(a.S,b)},c8=function(a,b){a8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.aN,this);this.u=(0,g.x)(this.vL,this);this.o=g.Co((0,g.x)(function(){isa(this,null)},this),12E4)},jsa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){b8(this,"Failed to send message: getMdxSessionStatus.")},a)):b8(a,"Sending yt message without session: "+g.Bj(b))},isa=function(a,b){g.Eo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.zn,a),d=(0,g.x)(a.Sd,a);a.jv(b,c,d,5)}}else a.Sd(Error("Waiting for session status timed out."))},d8=function(a,b,c){a8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.C=g.Ha;this.A=NaN;this.I=(0,g.x)(this.dN,this);this.g=g.Ha},ksa=function(a){a.g=a.F.DA(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.zn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Sd(b)},a))},lsa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}Tqa()&&(b.env_useStageMdx=1);return g.Df(b)},e8=function(a,b){a8.call(this,a,b,"ManualSession");
this.g=g.Co((0,g.x)(this.ii,this,null),150)},f8=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.aK,this)},msa=function(a,b){return b?g.Ya(a.l,function(c){return F6(b,c.label)},a):null},g8=function(a){L7("Controller",a)},Qra=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},h8=function(a){return a.u||!!a.l.length||!!a.g},i8=function(a,b,c){b!=a.g&&(g.Ei(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Cy,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.ii(null)):a.O("yt-remote-cast2-session-change",null))},nsa=function(a){var b=a.i.CA(),c=a.g&&a.g.i;
a=(0,g.A)(b,function(d){c&&F6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=msa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},tsa=function(a,b,c,d,e,f,k){osa()?psa(b,e,f,k)&&(k8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?qsa(a,c):(window.__onGCastApiAvailable=function(l,m){l?qsa(a,c):(l8("Failed to load cast API: "+m),m8(!1),k8(!1),C6("yt-remote-cast-available"),C6("yt-remote-cast-receiver"),rsa(),c(!1))},d?g.To("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?$qa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Y6():(Zqa(),X6(ssa.map(Xqa))))):j8("Cannot initialize because not running Chrome")},rsa=function(){j8("dispose");
var a=n8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);usa(!1);g.Oo(o8);o8.length=0},p8=function(){return!!g.ey("yt-remote-cast-installed")},vsa=function(){var a=g.ey("yt-remote-cast-receiver");
return a?a.friendlyName:null},wsa=function(){j8("clearCurrentReceiver");
C6("yt-remote-cast-receiver")},xsa=function(){return p8()?n8()?n8().getCastSession():(l8("getCastSelector: Cast is not initialized."),null):(l8("getCastSelector: Cast API is not installed!"),null)},r8=function(){p8()?n8()?q8()?(j8("Requesting cast selector."),n8().requestSession()):(j8("Wait for cast API to be ready to request the session."),o8.push(g.No("yt-remote-cast2-api-ready",r8))):l8("requestCastSelector: Cast is not initialized."):l8("requestCastSelector: Cast API is not installed!")},s8=
function(a,b){q8()?n8().setConnectedScreenStatus(a,b):l8("setConnectedScreenStatus called before ready.")},osa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ds||a},ysa=function(a,b){n8().init(a,b)},psa=function(a,b,c,d){var e=!1;
n8()||(a=new f8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.dy("yt-remote-cast-available",f);B6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){j8("onReceiverSelected: "+f.friendlyName);
g.dy("yt-remote-cast-receiver",f);B6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){j8("onReceiverResumed: "+f.friendlyName);
g.dy("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){j8("onSessionChange: "+I6(f));
f||C6("yt-remote-cast-receiver");B6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
j8("cloudview.createSingleton_: "+e);return e},n8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},qsa=function(a,b){m8(!0);
k8(!1);ysa(a,function(c){c?(usa(!0),g.Qo("yt-remote-cast2-api-ready")):(l8("Failed to initialize cast API."),m8(!1),C6("yt-remote-cast-available"),C6("yt-remote-cast-receiver"),rsa());b(c)})},j8=function(a){L7("cloudview",a)},l8=function(a){L7("cloudview",a)},m8=function(a){j8("setCastInstalled_ "+a);
g.dy("yt-remote-cast-installed",a)},q8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},usa=function(a){j8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},k8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},t8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Fe=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},u8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Fe=!1;a.hasNext=!1;a.C=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},v8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},w8=function(a,b){a.C=b;
a.A=(0,g.D)()},x8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},y8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&u8(a)},z8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.g);b.hasPrevious=a.Fe;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},B8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new Lra;this.l=this.i=null;this.F=(0,g.x)(this.WH,this);this.C=(0,g.x)(this.nk,this);this.D=(0,g.x)(this.VH,this);this.H=(0,g.x)(this.jI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Fs,this),zsa(this))):c=3;0!=c&&(b?this.Fs(c):g.Co((0,g.x)(function(){this.Fs(c)},this),0));
var d=xsa();d&&A8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},C8=function(a){return new t8(a.o.getPlayerContextData())},zsa=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.XJ,b),this))},a)},Asa=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},D8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},F8=function(a,b,c){var d=C8(a);
w8(d,c);-1E3!=d.playerState&&(d.playerState=b);E8(a,d)},G8=function(a,b,c){a.o.sendMessage(b,c)},E8=function(a,b){Asa(a);
a.o.setPlayerContextData(z8(b));zsa(a)},A8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.nk(null));
a.l=b;a.l&&(L7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.nk(a.l.media[0]))},Bsa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=C8(a);b.contentId!=d.videoId&&L7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;w8(d,a.i.getEstimatedTime());E8(a,d)}else L7("CP","No cast media video. Ignoring state update.")},H8=function(a,b,c){return(0,g.x)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),G8(this,b,c))},a)},I8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.S=[];this.o=this.A=this.l=this.Ra=this.g=null;this.R=a;this.S.push(g.cr(window,"beforeunload",(0,g.x)(this.JC,this)));this.i=[];this.Ra=new t8;this.N=b.id;this.g=Csa(this,c);this.g.subscribe("handlerOpened",this.aI,this);this.g.subscribe("handlerClosed",this.XH,this);this.g.subscribe("handlerError",this.YH,this);this.g.subscribe("handlerMessage",this.ZH,this);Pra(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ra.videoId;
g.gL()&&g.dy("yt-remote-session-video-id",d)},this)},J8=function(a){L7("conn",a)},Csa=function(a,b){return new F7(I7(a.R,"/bc"),b)},K8=function(a,b){a.O("proxyStateChange",b)},Dsa=function(a){a.u=g.Co((0,g.x)(function(){J8("Connecting timeout");
this.Kh(1)},a),2E4)},L8=function(a){g.Eo(a.u);
a.u=NaN},M8=function(a){g.Eo(a.H);
a.H=NaN},Esa=function(a){N8(a);
a.F=g.Co((0,g.x)(function(){O8(this,"getNowPlaying")},a),2E4)},N8=function(a){g.Eo(a.F);
a.F=NaN},Gsa=function(a,b){b&&(L8(a),M8(a));
b==(G7(a.g)&&isNaN(a.u))?b&&(K8(a,1),O8(a,"getSubtitlesTrack")):b?(a.gv()&&a.Ra.reset(),K8(a,1),O8(a,"getNowPlaying"),Fsa(a)):a.Kh(1)},Hsa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ra.videoId&&(g.Zb(b.params)?a.Ra.g=null:a.Ra.g=b.params,a.O("remotePlayerChange"))},Isa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ra.listId=b.params.listId||a.Ra.listId;y8(a.Ra,c,d);a.O("remoteQueueChange")},Ksa=function(a,b){b.params=b.params||{};
Isa(a,b);Jsa(a,b);a.O("autoplayDismissed")},Jsa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
w8(a.Ra,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ra.playerState&&(c=-1E3);a.Ra.playerState=c;c=Number(b.params.loadedTime);a.Ra.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Ra.D=isNaN(c)?0:c;c=a.Ra;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Ra;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Ra.playerState?Esa(a):N8(a);a.O("remotePlayerChange")},Lsa=function(a,b){if(-1E3!=
a.Ra.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ra.playerState=c;c=parseInt(b.params.currentTime,10);w8(a.Ra,isNaN(c)?0:c);a.O("remotePlayerChange")}},Msa=function(a,b){var c="true"==b.params.muted;
a.Ra.volume=parseInt(b.params.volume,10);a.Ra.muted=c;a.O("remotePlayerChange")},Nsa=function(a,b){a.A=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},Osa=function(a,b){var c="true"==b.params.hasNext;
a.Ra.Fe="true"==b.params.hasPrevious;a.Ra.hasNext=c;a.O("previousNextChange")},Fsa=function(a){g.Eo(a.D);
a.D=g.Co((0,g.x)(a.Kh,a,1),864E5)},O8=function(a,b,c){c?J8("Sending: action="+b+", params="+g.Bj(c)):J8("Sending: action="+b);
a.g.sendMessage(b,c)},P8=function(a){P7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.YM,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.BJ,this)))},Tsa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.uo("MDX_CONFIG")||b;Kqa();R6();Q8||(Q8=new H7(b?b.loungeApiHost:void 0),Tqa()&&(Q8.g="/api/loungedev"));R8||(R8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",R8,void 0));Psa();var c=S8();if(!c){var d=new Y7(Q8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=S8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);tsa(a,d,function(m){m?T8()&&s8(T8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){B6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),U8("Initializing: "+g.Bj(b)),V8.push(g.No("yt-remote-cast2-availability-change",function(){B6("yt-remote-receiver-availability-change")})),V8.push(g.No("yt-remote-cast2-receiver-selected",function(){W8(null);
B6("yt-remote-auto-connect","cast-selector-receiver")})),V8.push(g.No("yt-remote-cast2-receiver-resumed",function(){B6("yt-remote-receiver-resumed","cast-selector-receiver")})),V8.push(g.No("yt-remote-cast2-session-change",Qsa)),V8.push(g.No("yt-remote-connection-change",function(m){m?s8(T8(),"YouTube TV"):X8()||(s8(null,null),wsa())})),a=Y8(),b.isAuto&&(a.id+="#dial"),g.vp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),U8(" -- with channel params: "+
g.Bj(a)),Rsa(a),c.start(),T8()||Ssa())},Vsa=function(){var a=Usa();
p8()&&g.ey("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Usa=function(){var a=S8().Vc.$_gos();
var b=Z8();b&&$8()&&(L6(a,b)||a.push(b));return Pqa(a)},a9=function(){var a=Wsa();
!a&&p8()&&vsa()&&(a={key:"cast-selector-receiver",name:vsa()});return a},Wsa=function(){var a=Usa(),b=Z8();
b||(b=X8());return g.Ya(a,function(c){return b&&F6(b,c.key)?!0:!1})},Z8=function(){var a=T8();
if(!a)return null;var b=S8().Qd();return M6(b,a)},Qsa=function(a){U8("remote.onCastSessionChange_: "+I6(a));
if(a){var b=Z8();b&&b.id==a.id?s8(b.id,"YouTube TV"):(b&&b9(),c9(a,1))}else $8()&&b9()},b9=function(){q8()?n8().stopSession():l8("stopSession called before API ready.");
var a=$8();a&&(a.disconnect(1),d9(null))},e9=function(){var a=$8();
return!!a&&3!=a.getProxyState()},U8=function(a){L7("remote",a)},S8=function(){if(!f9){var a=g.w("yt.mdx.remote.screenService_");
f9=a?new P8(a):null}return f9},T8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Xsa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Ysa=function(){return g.w("yt.mdx.remote.connectData_")},W8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},$8=function(){return g.w("yt.mdx.remote.connection_")},d9=function(a){var b=$8();
W8(null);a||Xsa("");g.Ga("yt.mdx.remote.connection_",a,void 0);R8&&((0,g.z)(R8,function(c){c(a)}),R8.length=0);
b&&!a?B6("yt-remote-connection-change",!1):!b&&a&&B6("yt-remote-connection-change",!0)},X8=function(){var a=g.gL();
if(!a)return null;var b=S8().Qd();return M6(b,a)},c9=function(a,b){T8();
Z8()&&Z8();if(g9)h9=a;else{Xsa(a.id);var c=new I8(Q8,a,Y8());c.connect(b,Ysa());c.subscribe("beforeDisconnect",function(d){B6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){$8()&&($8(),d9(null))});
d9(c)}},Ssa=function(){var a=X8();
a?(U8("Resume connection to: "+I6(a)),c9(a,0)):(V6(),wsa(),U8("Skipping connecting because no session screen found."))},Psa=function(){var a=Y8();
if(g.Zb(a)){a=Q6();var b=g.ey("yt-remote-session-name")||"",c=g.ey("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},Y8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Rsa=function(a){a?(g.dy("yt-remote-session-app",a.app),g.dy("yt-remote-session-name",a.name)):(C6("yt-remote-session-app"),C6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.I.call(this);
this.u=a;this.i=b;this.l=new g.Ks(this);g.J(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.XI);this.l.K(b,"captionschanged",this.UH);this.l.K(b,"captionssettingschanged",this.Pz);this.l.K(b,"videoplayerreset",this.An);this.l.K(b,"mdxautoplaycancel",this.KB);this.R=this.l.K(b,"onVolumeChange",this.jy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.yy,this);c.subscribe("remotePlayerChange",this.qk,this);c.subscribe("remoteQueueChange",this.An,this);c.subscribe("autoplayUpNext",this.Xx,
this);c.subscribe("previousNextChange",this.uy,this);c.subscribe("nowAutoplaying",this.oy,this);c.subscribe("autoplayDismissed",this.Wx,this);this.suggestion=null;this.F=new g.At(64);this.o=new g.K(this.Nz,500,this);g.J(this,this.o);this.A=new g.K(this.Oz,1E3,this);g.J(this,this.A);this.I=new Z6(this.CM,0,this);g.J(this,this.I);this.C={};this.S=new g.K(this.pA,1E3,this);g.J(this,this.S);this.H=new g.ml(this.pF,1E3,this);g.J(this,this.H);this.N=g.Ha;this.Pz();this.An();this.qk()},j9=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.S=b||0;c.player.O("progresssync",b,d)},Zsa=function(a){j9(a,0);
a.o.stop();k9(a,new g.At(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.gc(c,b));a.g.Dz(a.i.getVideoData(1).videoId,c);a.C=C8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ua;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.He,x6(c));k9(a,new g.At(1))},$sa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{BQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return C8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.A.stop();
var c=a.F;if(!g.Gt(c,b)){var d=g.S(b,2);d!=g.S(a.F,2)&&g.aS(a.i.app,d);a.F=b;ata(a.u,c,b)}},o9=function(){g.U.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.mL(this,250);g.J(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},p9=function(a){g.U.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.oL()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.mL(this,250);g.J(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);bta(this,g.jK(a))},bta=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.TL("Error on $RECEIVER_NAME",c):g.Ht(b)||g.S(b,4)?g.TL("Playing on $RECEIVER_NAME",c):g.TL("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.PN.call(this,"Play on",0,a,b);
this.l=a;this.C={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},r9=function(a){g.YO.call(this,a);
this.i={key:K6(),name:"This computer"};this.u=null;this.o=[];this.N=this.g=null;this.H=[this.i];this.l=this.i;this.C=new g.At(64);this.S=0;this.F=-1;this.A=null;if(!g.bz(this.player.M())){a=this.player;var b=g.UC(a);b&&(b=b.en())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.BK(a,b.element,4);this.A=new o9;g.J(this,this.A);g.BK(a,this.A.element,4);this.I=!!X8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},ata=function(a,b,c){a.C=
c;
a.player.O("presentingplayerstatechange",new g.kD(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)b9();
else{var c;(c=!g.Q(a.player.M().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.uo("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.uo("SESSION_INDEX")&&!g.uo("LOGGED_IN")))||a.I||!a.A);if(c?0:"WEB"==a.player.M().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.M().deviceParams.c)g.Ht(g.jK(a.player))?a.player.pauseVideo():(a.D=(0,g.x)(a.AL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.A&&a.A.l.show(),$8()||(g9=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.He,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=x6(c))&&(d.locationInfo=c);c=d}else c=null;U8("Connecting to: "+g.Bj(b));"cast-selector-receiver"==b.key?(W8(c||null),c=c||null,q8()?n8().setLaunchParams(c):l8("setLaunchParams called before ready.")):
!c&&e9()&&T8()==b.key?B6("yt-remote-connection-change",!0):(b9(),W8(c||null),c=S8().Qd(),(c=M6(c,b.key))&&c9(c,1))}},ira={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},k7={"'":"\\'"},cta={},Nqa={xN:"atp",NP:"ska",CP:"que",bP:"mus",MP:"sus",tO:"dsp",JP:"seq"};
D6.prototype.ag=function(){var a=new D6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var W6,P6="",Yqa=Uqa("loadCastFramework")||Uqa("loadCastApplicationFramework"),ssa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(Z6,g.I);g.h=Z6.prototype;g.h.FC=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Wc:this.Ca=g.kl(this.u,this.Wc)};
g.h.stop=function(){this.Ca&&(g.u.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.W=function(){this.stop();Z6.fb.W.call(this)};
g.h.GC=function(){this.l?(this.Ca=g.kl(this.u,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};a7.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
a7.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};b7.prototype.g=null;b7.prototype.getOptions=function(){var a;(a=this.g)||(a={},bra(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Ta(ara,b7);u9=new ara;g.h=c7.prototype;g.h.Wg=null;g.h.we=!1;g.h.Ri=null;g.h.Cs=null;g.h.Bi=null;g.h.Th=null;g.h.Tf=null;g.h.Bg=null;g.h.oh=null;g.h.wc=null;g.h.Tk=0;g.h.Ae=null;g.h.mo=null;g.h.mg=null;g.h.Fj=-1;g.h.yz=!0;g.h.Lg=!1;g.h.Lp=0;g.h.Fn=null;var gra={},f7={};g.h=c7.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.ML=function(a){a=a.target;var b=this.Fn;b&&3==t7(a)?b.Bj():this.xA(a)};
g.h.xA=function(a){try{if(a==this.wc)a:{var b=t7(this.wc),c=this.wc.u,d=this.wc.getStatus();if(g.Md&&!g.od(10)||g.Od&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cg&&!v7(this.wc))break a;this.Lg||4!=b||7==c||(8==c||0>=d?this.g.ue(3):this.g.ue(2));m7(this);var e=this.wc.getStatus();this.Fj=e;var f=v7(this.wc);(this.we=200==e)?(4==b&&i7(this),this.u?(hra(this,b,f),g.cg&&this.we&&3==b&&(this.ca.da(this.i,"tick",this.GL),this.i.start())):h7(this,f),this.we&&!this.Lg&&(4==b?this.g.xn(this):(this.we=
!1,e7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mg=3,g7(13)):(this.mg=0,g7(14)),i7(this),j7(this))}}catch(k){this.wc&&v7(this.wc)}finally{}};
g.h.GL=function(){var a=t7(this.wc),b=v7(this.wc);this.Tk<b.length&&(m7(this),hra(this,a,b),this.we&&4!=a&&e7(this))};
g.h.bL=function(a){l7((0,g.x)(this.aL,this,a),0)};
g.h.aL=function(a){this.Lg||(m7(this),h7(this,a),e7(this))};
g.h.Fy=function(a){l7((0,g.x)(this.ZK,this,a),0)};
g.h.ZK=function(a){this.Lg||(i7(this),this.we=a,this.g.xn(this),this.g.ue(4))};
g.h.cancel=function(){this.Lg=!0;i7(this)};
g.h.kL=function(){this.Ri=null;var a=(0,g.D)();0<=a-this.Cs?(2!=this.Th&&this.g.ue(3),i7(this),this.mg=2,g7(18),j7(this)):kra(this,this.Cs-a)};
g.h.getLastError=function(){return this.mg};g.h=nra.prototype;g.h.Jp=null;g.h.Gd=null;g.h.Gn=!1;g.h.uv=null;g.h.Vl=null;g.h.mq=null;g.h.Kp=null;g.h.ge=null;g.h.zf=-1;g.h.Ej=null;g.h.bj=null;g.h.connect=function(a){this.Kp=a;a=o7(this.g,null,this.Kp);g7(3);this.uv=(0,g.D)();var b=this.g.D;null!=b?(this.Ej=b[0],(this.bj=b[1])?(this.ge=1,ora(this)):(this.ge=2,q7(this))):(w6(a,"MODE","init"),this.Gd=new c7(this,void 0,void 0,void 0),this.Gd.Wg=this.Jp,d7(this.Gd,a,!1,null,!0),this.ge=0)};
g.h.LB=function(a){if(a)this.ge=2,q7(this);else{g7(4);var b=this.g;b.Ee=b.Zf.zf;C7(b,9)}a&&this.ue(2)};
g.h.gp=function(a){return this.g.gp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.zf=-1};
g.h.tv=function(){return!1};
g.h.zy=function(a,b){this.zf=a.Fj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.zf;C7(c,2);return}this.Ej=c[0];this.bj=c[1]}else c=this.g,c.Ee=this.zf,C7(c,2);else if(2==this.ge)if(this.Gn)g7(7),this.mq=(0,g.D)();else if("11111"==b){if(g7(6),this.Gn=!0,this.Vl=(0,g.D)(),c=this.Vl-this.uv,!g.Md||g.od(10)||500>c)this.zf=200,this.Gd.cancel(),g7(12),p7(this.g,this,!0)}else g7(8),this.Vl=this.mq=(0,g.D)(),this.Gn=!1};
g.h.xn=function(){this.zf=this.Gd.Fj;if(this.Gd.we)0==this.ge?this.bj?(this.ge=1,ora(this)):(this.ge=2,q7(this)):2==this.ge&&((!g.Md||g.od(10)?!this.Gn:200>this.mq-this.Vl)?(g7(11),p7(this.g,this,!1)):(g7(12),p7(this.g,this,!0)));else{0==this.ge?g7(9):2==this.ge&&g7(10);var a=this.g;this.Gd.getLastError();a.Ee=this.zf;C7(a,2)}};
g.h.Fk=function(){return this.g.Fk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ue=function(a){this.g.ue(a)};g.Ta(r7,g.zk);var tra=/^https?$/i,dta=["POST","PUT"];g.h=r7.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.aa=b;this.R=!1;this.i=!0;this.g=this.N?cra(this.N):cra(u9);this.S=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.x)(this.vv,this);try{A6(u7(this,"Opening Xhr")),this.ba=!0,this.g.open(b,String(a),!0),this.ba=!1}catch(f){A6(u7(this,"Error opening Xhr: "+f.message));sra(this,f);return}a=
c||"";var e=this.headers.clone();d&&Iqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.de(),qra);c=g.u.FormData&&a instanceof g.u.FormData;!g.ab(dta,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{vra(this),0<this.A&&(this.I=pra(this.g),A6(u7(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.wv,this)):this.F=g.kl(this.wv,this.A,this)),A6(u7(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){A6(u7(this,"Send error: "+f.message)),sra(this,f)}};
g.h.wv=function(){"undefined"!=typeof g.nZ&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,u7(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(u7(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),s7(this))};
g.h.W=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),s7(this,!0));r7.fb.W.call(this)};
g.h.vv=function(){this.ga()||(this.ba||this.C||this.o?ura(this):this.ZJ())};
g.h.ZJ=function(){ura(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<t7(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};g.h=w7.prototype;g.h.oj=null;g.h.Ad=null;g.h.Rb=null;g.h.Ip=null;g.h.Xl=null;g.h.Rt=null;g.h.pm=null;g.h.kk=0;g.h.nH=0;g.h.Tc=null;g.h.jg=null;g.h.lf=null;g.h.Pg=null;g.h.Zf=null;g.h.ko=null;g.h.hi=-1;g.h.ew=-1;g.h.Ee=-1;g.h.Mh=0;g.h.Gh=0;g.h.Mg=8;var D7=new g.zk;g.Ta(xra,g.ak);g.Ta(yra,g.ak);g.Ta(zra,g.ak);g.h=w7.prototype;g.h.connect=function(a,b,c,d,e){g7(0);this.Ip=b;this.oj=c||{};d&&g.Ca(e)&&(this.oj.OSID=d,this.oj.OAID=e);this.A?(l7((0,g.x)(this.mu,this,a),100),Dra(this)):this.mu(a)};
g.h.mu=function(a){this.Zf=new nra(this);this.Zf.Jp=null;this.Zf.i=this.u;this.Zf.connect(a)};
g.h.tv=function(){return 0==this.g};
g.h.Ey=function(a){this.jg=null;Gra(this,a)};
g.h.Dy=function(){this.lf=null;this.Rb=new c7(this,this.l,"rpc",this.C);this.Rb.Wg=null;this.Rb.Lp=0;var a=this.Rt.clone();u6(a,"RID","rpc");u6(a,"SID",this.l);u6(a,"CI",this.ko?"0":"1");u6(a,"AID",this.hi);x7(this,a);if(!g.Md||g.od(10))u6(a,"TYPE","xmlhttp"),d7(this.Rb,a,!0,this.pm,!1);else{u6(a,"TYPE","html");var b=this.Rb,c=!!this.pm;b.Th=3;b.Tf=v6(a.clone());jra(b,c)}};
g.h.zy=function(a,b){if(0!=this.g&&(this.Rb==a||this.Ad==a))if(this.Ee=a.Fj,this.Ad==a&&3==this.g)if(7<this.Mg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.lf){if(this.Rb)if(this.Rb.Bi+3E3<this.Ad.Bi)z7(this),this.Rb.cancel(),this.Rb=null;else break a;B7(this);g7(19)}}else this.ew=c[1],0<this.ew-this.hi&&37500>c[2]&&this.ko&&0==this.Gh&&!this.Pg&&(this.Pg=l7((0,g.x)(this.QH,this),6E3));else C7(this,11)}else b!=cta.UN.g&&C7(this,11);else if(this.Rb==a&&
z7(this),!g.xb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.hi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.pm=e[2],e=e[3],null!=e?this.Mg=e:this.Mg=6,this.g=3,this.Tc&&this.Tc.gu(),this.Rt=o7(this,this.Fk()?this.pm:null,this.Ip),Hra(this)):"stop"==e[0]&&C7(this,7):3==this.g&&("stop"==e[0]?C7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.fu(e),this.Gh=0)}}};
g.h.QH=function(){null!=this.Pg&&(this.Pg=null,this.Rb.cancel(),this.Rb=null,B7(this),g7(20))};
g.h.xn=function(a){if(this.Rb==a){z7(this);this.Rb=null;var b=2}else if(this.Ad==a)this.Ad=null,b=1;else return;this.Ee=a.Fj;if(0!=this.g)if(a.we)1==b?(b=(0,g.D)()-a.Bi,D7.dispatchEvent(new yra(D7,a.oh?a.oh.length:0,b,this.Mh)),y7(this),this.o.length=0):Hra(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.Ad||this.jg||1==this.g||2<=this.Mh?d=!1:(this.jg=l7((0,g.x)(this.Ey,this,a),Ira(this,this.Mh)),this.Mh++,d=!0);d=!(d||2==b&&B7(this))}if(d)switch(c){case 1:C7(this,
5);break;case 4:C7(this,10);break;case 3:C7(this,6);break;case 7:C7(this,12);break;default:C7(this,2)}}};
g.h.fC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.tM=function(a){a?g7(2):(g7(1),Jra(this,8))};
g.h.gp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new r7;a.T=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.ue=function(a){D7.dispatchEvent(new zra(D7,a))};
g.h.Fk=function(){return!(!g.Md||g.od(10))};
g.h=Kra.prototype;g.h.gu=function(){};
g.h.fu=function(){};
g.h.eu=function(){};
g.h.Xo=function(){};
g.h.Ru=function(){return{}};
g.h.isActive=function(){return!0};g.h=Lra.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.tna)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.Cd=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ta(E7,g.I);g.h=E7.prototype;g.h.SK=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.fn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.Ta(F7,Kra);g.h=F7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.l.Xg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Ei(this.l),Ora(this),g.Ei(this.i),this.i=null)};
g.h.ga=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new w7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.hi):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):G7(this)&&Era(this.g,c)};
g.h.gu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)Era(this.g,a[b])}this.O("handlerOpened")};
g.h.eu=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.Xo=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Ru=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.gc(a,this.u);return a};
g.h.fu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),Cra(this.g)):this.O("handlerMessage",new Mra(a[0],a[1]))};
g.h.WL=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.Ad&&b++;0==b&&this.connect(this.u,this.o)};H7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
H7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
H7.prototype.u=function(a){a(Error("request timed out"))};var Wra=(0,g.D)(),K7=null,N7=Array(50),M7=-1,O7=!1;g.Ta(P7,g.P);P7.prototype.Qd=function(){return this.g};
P7.prototype.contains=function(a){return!!L6(this.g,a)};
P7.prototype.get=function(a){return a?M6(this.g,a):null};
P7.prototype.info=function(a){L7(this.C,a)};g.t(Q7,g.P);g.h=Q7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.BA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.Eo(this.Ca),this.Ca=NaN)};
g.h.W=function(){this.stop();g.P.prototype.W.call(this)};
g.h.BA=function(){this.Ca=NaN;this.g=g.Ep(I7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.WM,this),onError:(0,g.x)(this.VM,this),Td:(0,g.x)(this.XM,this)})};
g.h.WM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new E6(c))};
g.h.VM=function(a){this.g=null;a.status&&404==a.status?this.i>=eta.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=eta[this.i],this.Ca=g.Co((0,g.x)(this.BA,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.XM=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var eta=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(S7,P7);g.h=S7.prototype;g.h.start=function(){R7(this)&&this.O("screenChange");!g.ey("yt-remote-lounge-token-expiration")&&$ra(this);g.Eo(this.i);this.i=g.Co((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){R7(this);Xra(this,a);T7(this,!1);this.O("screenChange");b(a);a.token||$ra(this)};
g.h.remove=function(a,b){var c=R7(this);Zra(this,a)&&(T7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.eo=function(a,b,c,d){var e=R7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,T7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.W=function(){g.Eo(this.i);S7.fb.W.call(this)};
g.h.QC=function(a){R7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}T7(this,!b);b&&L7(this.C,"Missed "+b+" lounge tokens.")};
g.h.PC=function(a){L7(this.C,"Requesting lounge tokens failed: "+a)};g.t(V7,g.P);g.h=V7.prototype;g.h.start=function(){var a=parseInt(g.ey("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?X7(this):(this.o=(0,g.D)()+3E5,g.dy("yt-remote-fast-check-period",this.o),this.Ir())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){U7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!M6(a,d)},this);
W7(this,b)};
g.h.W=function(){g.Eo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.W.call(this)};
g.h.Ir=function(){g.Eo(this.l);this.l=NaN;this.i&&this.i.abort();var a=csa(this);if(y6(a)){var b=I7(this.u,"/pairing/get_screen_availability");this.i=J7(this.u,b,{lounge_token:g.Tb(a).join(",")},(0,g.x)(this.vK,this,a),(0,g.x)(this.uK,this))}else W7(this,{}),X7(this)};
g.h.vK=function(a,b){this.i=null;var c=g.Tb(csa(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;W7(this,d);X7(this)}else this.Jb("Changing Screen set during request."),this.Ir()};
g.h.uK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;X7(this)};
g.h.Jb=function(a){L7("OnlineScreenService",a)};g.Ta(Y7,P7);g.h=Y7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.eo=function(a,b,c,d){this.l.contains(a)?this.l.eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,L7(this.C,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.CA=function(){return(0,g.Yd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.DA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new Q7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ei(f);d(Z7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ei(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.ZM=function(a,b,c,d){g.Ep(I7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new E6(f.screen||{});if(!k.name||gsa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);gsa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(Z7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Td:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Ei(this.l);g.Ei(this.i);Y7.fb.W.call(this)};
g.h.YC=function(){hsa(this);this.O("screenChange");this.i.update()};
Y7.prototype.dispose=Y7.prototype.dispose;g.Ta(a8,g.P);g.h=a8.prototype;g.h.zn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Sd=function(a){this.ga()||(a&&b8(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){L7(this.S,a)};
g.h.FA=function(){return null};
g.h.Qr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){b8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Qr("");a8.fb.W.call(this)};g.Ta(c8,a8);g.h=c8.prototype;g.h.Pr=function(a){if(this.g){if(this.g==a)return;b8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);jsa(this)};
g.h.ii=function(a){this.info("launchWithParams no-op for Cast: "+g.Bj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Sd()},this),(0,g.x)(function(){this.Sd(Error("Failed to stop receiver app."))},this)):this.Sd(Error("Stopping cast device witout session."))};
g.h.Qr=g.Ha;g.h.W=function(){this.info("disposeInternal");g.Eo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;c8.fb.W.call(this)};
g.h.vL=function(a,b){if(!this.ga())if(b){var c=$6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bj(c));switch(d){case "mdxSessionStatus":isa(this,c.screenId);break;default:b8(this,"Unknown youtube message: "+d)}}else b8(this,"Unable to parse message.")}else b8(this,"No data in message.")};
g.h.jv=function(a,b,c,d){fsa(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(b8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Co((0,g.x)(this.jv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.FA=function(){return this.g};
g.h.aN=function(a){this.ga()||a||(b8(this,"Cast session died."),this.Sd())};g.Ta(d8,a8);g.h=d8.prototype;g.h.Pr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ii=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Eo(this.A);this.o?this.o.stop((0,g.x)(this.Sd,this,null),(0,g.x)(this.Sd,this,"Failed to stop DIAL device.")):this.Sd()};
g.h.W=function(){this.g();this.g=g.Ha;g.Eo(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;d8.fb.W.call(this)};
g.h.dN=function(a){this.ga()||a||(b8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Sd())};
g.h.Wp=function(a){this.H=K6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,lsa(this));a(b);ksa(this)}else this.C=(0,g.x)(function(){g.Eo(this.A);this.C=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,lsa(this));a(c);ksa(this)},this),this.A=g.Co((0,g.x)(function(){this.C()},this),100)};
g.h.tD=function(a,b,c){fsa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.zn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Wp(b,c)},this),(0,g.x)(function(d){b8(this,"Failed to get DIAL screen: "+d);
this.Wp(b,c)},this))};g.Ta(e8,a8);e8.prototype.stop=function(){this.Sd()};
e8.prototype.Pr=g.Ha;e8.prototype.ii=function(){g.Eo(this.g);this.g=NaN;var a=M6(this.F.Qd(),this.i.label);a?this.zn(a):this.Sd(Error("No such screen"))};
e8.prototype.W=function(){g.Eo(this.g);this.g=NaN;e8.fb.W.call(this)};g.Ta(f8,g.P);g.h=f8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.eK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.By,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.qI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),Tra(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.EA,this)),this.l=nsa(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Jb("Failed to set initial custom receivers: "+g.Bj(k))},this)),this.O("yt-remote-cast2-availability-change",h8(this)),b(!0))},this),(0,g.x)(function(k){this.Jb("Failed to initialize API: "+g.Bj(k));
b(!1)},this))};
g.h.eM=function(a,b){g8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)g8("Unsetting old screen status: "+this.g.i.friendlyName),i8(this,null)}if(a&&b){if(!this.g){c=M6(this.i.Qd(),a);if(!c){g8("setConnectedScreenStatus: Unknown screen.");return}var d=msa(this,c);d||(g8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Bj(e))},this)));
g8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);i8(this,new e8(this.i,d),!0)}this.g.Qr(b)}else g8("setConnectedScreenStatus: no screen.")};
g.h.fM=function(a){this.ga()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.ii(a):this.Jb("Setting connection data without a session")};
g.h.cN=function(){this.ga()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),i8(this,null)):g8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.By,this),(0,g.x)(this.BK,this))};
g.h.W=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.EA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);var a=Qra,b=g.w("yt.mdx.remote.debug.handlers_");g.eb(b||[],a);g.Ei(this.g);f8.fb.W.call(this)};
g.h.Jb=function(a){L7("Controller",a)};
g.h.Cy=function(a,b){this.g==a&&(b||i8(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.aK=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),g8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)g8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{g8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:i8(this,
new e8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:i8(this,new d8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:i8(this,new c8(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.qI=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return g8("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);i8(this,new d8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.tD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Wp,b))};
g.h.By=function(a){if(!this.ga()){g8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)g8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),i8(this,new c8(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=M6(this.i.Qd(),c.label);d&&F6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(g8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ei(this.g),this.g=new c8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Cy,this,this.g)),this.g.ii(null));this.g.Pr(a)}}};
g.h.bN=function(){return this.g?this.g.FA():null};
g.h.BK=function(a){this.ga()||(this.Jb("Failed to estabilish a session: "+g.Bj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&i8(this,null))};
g.h.eK=function(a){g8("Receiver availability updated: "+a);if(!this.ga()){var b=h8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;h8(this)!=b&&this.O("yt-remote-cast2-availability-change",h8(this))}};
g.h.EA=function(){this.ga()||(this.l=nsa(this),g8("Updating custom receivers: "+g.Bj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Jb("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",h8(this)))};
f8.prototype.setLaunchParams=f8.prototype.fM;f8.prototype.setConnectedScreenStatus=f8.prototype.eM;f8.prototype.stopSession=f8.prototype.cN;f8.prototype.getCastSession=f8.prototype.bN;f8.prototype.requestSession=f8.prototype.requestSession;f8.prototype.init=f8.prototype.init;f8.prototype.dispose=f8.prototype.dispose;var o8=[];t8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";u8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Fe=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
t8.prototype.isAdPlaying=function(){return 1081==this.playerState};
t8.prototype.getDuration=function(){return this.u?this.D+v8(this):this.D};
t8.prototype.clone=function(){return new t8(z8(this))};g.t(B8,g.P);g.h=B8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,H8(this,"play")):G8(this,"play"),F8(this,1,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,H8(this,"pause")):G8(this,"pause"),F8(this,2,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=C8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,H8(this,"seekTo",{newTime:a}))}else G8(this,"seekTo",{newTime:a});F8(this,3,a);this.O("remotePlayerChange")}else D8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,H8(this,"stopVideo")):G8(this,"stopVideo");var a=C8(this);a.index=-1;a.videoId="";u8(a);E8(this,a);this.O("remotePlayerChange")}else D8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=C8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){L7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){L7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);G8(this,"setVolume",e)}c.muted=b;c.volume=a;E8(this,c)}else D8(this,g.Ra(this.setVolume,a,b))};
g.h.Dz=function(a,b){if(1==this.g){var c=C8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Bj(b.style),g.gc(d,c.g));G8(this,"setSubtitlesTrack",d);E8(this,c)}else D8(this,g.Ra(this.Dz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();G8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=C8(this);d.audioTrackId=c;E8(this,d)}else D8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=C8(this);c=c||0;var m={videoId:a,currentIndex:c};y8(l,a,c);g.Ca(b)&&(w8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Bj(k));G8(this,"setPlaylist",m);d||E8(this,l)};
g.h.AA=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"previous")}else D8(this,g.Ra(this.AA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"next")}else D8(this,g.Ra(this.nextVideo,a,b))};
g.h.vu=function(){1==this.g?G8(this,"dismissAutoplay"):D8(this,this.vu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.W=function(){Asa(this);this.o=null;this.u.clear();A8(this,null);g.P.prototype.W.call(this)};
g.h.Fs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.XJ=function(a,b){this.O(a,b)};
g.h.WH=function(a){if(!a)this.nk(null),A8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=C8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)L7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,E8(this,b)}};
g.h.nk=function(a){L7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Bsa(this),this.O("remotePlayerChange")};
g.h.VH=function(a){a?(Bsa(this),this.O("remotePlayerChange")):this.nk(null)};
g.h.jI=function(){var a=xsa();a&&A8(this,a)};
g.h.Jb=function(a){L7("CP",a)};g.t(I8,g.P);g.h=I8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Ra.listId=c);this.Ra.videoId=d;this.Ra.index=k||0;this.Ra.state=3;w8(this.Ra,m);this.o="UNSUPPORTED";J8("Connecting with setPlaylist and params: "+g.Bj(l));this.g.connect({method:"setPlaylist",
params:g.Bj(l)},a,S6())}else J8("Connecting without params"),this.g.connect({},a,S6());Dsa(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),K8(this,3));g.P.prototype.dispose.call(this)};
g.h.W=function(){L8(this);N8(this);M8(this);g.Eo(this.C);this.C=NaN;g.Eo(this.D);this.D=NaN;this.l=null;g.dr(this.S);this.S.length=0;this.g.dispose();g.P.prototype.W.call(this);this.o=this.A=this.i=this.Ra=this.g=null};
g.h.JC=function(){this.Kh(2)};
g.h.aI=function(){J8("Channel opened");this.I&&(this.I=!1,M8(this),this.H=g.Co((0,g.x)(function(){J8("Timing out waiting for a screen.");this.Kh(1)},this),15E3));
Sqa(Nra(this.g),this.N)};
g.h.XH=function(){J8("Channel closed");isNaN(this.u)?V6(!0):V6();this.dispose()};
g.h.YH=function(a){V6();isNaN(this.wj())?(J8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,J8("Channel error: "+a+" with reconnection in "+this.wj()+" ms"),K8(this,2))};
g.h.ZH=function(a){a.params?J8("Received: action="+a.action+", params="+g.Bj(a.params)):J8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=$6(a.params.devices);this.i=(0,g.A)(a,function(c){return new D6(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Gsa(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Gsa(this,!1);break;case "remoteConnected":var b=new D6($6(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||Fqa(this.i,b);
break;case "remoteDisconnected":b=new D6($6(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Isa(this,a);break;case "nowPlaying":Ksa(this,a);break;case "onStateChange":Jsa(this,a);break;case "onAdStateChange":Lsa(this,a);break;case "onVolumeChanged":Msa(this,a);break;case "onSubtitlesTrackChanged":Hsa(this,a);break;case "nowAutoplaying":Nsa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.O("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Osa(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:J8("Unrecognized action: "+a.action)}};
g.h.TL=function(){if(this.l){var a=this.l;this.l=null;this.Ra.videoId!=a&&O8(this,"getNowPlaying")}};
g.h.zC=function(){var a=3;this.ga()||(a=0,isNaN(this.wj())?G7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Kh=function(a){J8("Disconnecting with "+a);L8(this);this.O("beforeDisconnect",a);1==a&&V6();Ora(this.g,a);this.dispose()};
g.h.yC=function(){var a=this.Ra;this.l&&(a=this.Ra.clone(),y8(a,this.l,a.index));return z8(a)};
g.h.gM=function(a){var b=new t8(a);b.videoId&&b.videoId!=this.Ra.videoId&&(this.l=b.videoId,g.Eo(this.C),this.C=g.Co((0,g.x)(this.TL,this),5E3));var c=[];this.Ra.listId==b.listId&&this.Ra.videoId==b.videoId&&this.Ra.index==b.index||c.push("remoteQueueChange");this.Ra.playerState==b.playerState&&this.Ra.volume==b.volume&&this.Ra.muted==b.muted&&x8(this.Ra)==x8(b)&&g.Bj(this.Ra.g)==g.Bj(b.g)||c.push("remotePlayerChange");this.Ra.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.gv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.wj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.sC=function(){return this.o||"UNSUPPORTED"};
g.h.tC=function(){return this.A||""};
g.h.UM=function(){if(!isNaN(this.wj())){var a=this.g.i;g.gn(a.g);a.start()}};
g.h.bM=function(a,b){O8(this,a,b);Fsa(this)};
I8.prototype.subscribe=I8.prototype.subscribe;I8.prototype.unsubscribeByKey=I8.prototype.Hf;I8.prototype.getProxyState=I8.prototype.zC;I8.prototype.disconnect=I8.prototype.Kh;I8.prototype.getPlayerContextData=I8.prototype.yC;I8.prototype.setPlayerContextData=I8.prototype.gM;I8.prototype.getOtherConnectedRemoteId=I8.prototype.gv;I8.prototype.getReconnectTimeout=I8.prototype.wj;I8.prototype.getAutoplayMode=I8.prototype.sC;I8.prototype.getAutoplayVideoId=I8.prototype.tC;I8.prototype.reconnect=I8.prototype.UM;
I8.prototype.sendMessage=I8.prototype.bM;g.t(P8,P7);g.h=P8.prototype;g.h.Qd=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;P7.prototype.W.call(this)};
g.h.YM=function(){this.O("screenChange")};
g.h.BJ=function(){this.O("onlineScreenChange")};
Y7.prototype.$_st=Y7.prototype.start;Y7.prototype.$_gspc=Y7.prototype.ZM;Y7.prototype.$_gsppc=Y7.prototype.DA;Y7.prototype.$_c=Y7.prototype.contains;Y7.prototype.$_g=Y7.prototype.get;Y7.prototype.$_a=Y7.prototype.add;Y7.prototype.$_un=Y7.prototype.eo;Y7.prototype.$_r=Y7.prototype.remove;Y7.prototype.$_gs=Y7.prototype.Qd;Y7.prototype.$_gos=Y7.prototype.CA;Y7.prototype.$_s=Y7.prototype.subscribe;Y7.prototype.$_ubk=Y7.prototype.Hf;var h9=null,g9=!1,Q8=null,R8=null,f9=null,V8=[];g.t(i9,g.I);g.h=i9.prototype;
g.h.W=function(){g.I.prototype.W.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.yy,this);this.g.unsubscribe("remotePlayerChange",this.qk,this);this.g.unsubscribe("remoteQueueChange",this.An,this);this.g.unsubscribe("autoplayUpNext",this.Xx,this);this.g.unsubscribe("previousNextChange",this.uy,this);this.g.unsubscribe("nowAutoplaying",this.oy,this);this.g.unsubscribe("autoplayDismissed",this.Wx,this);this.g=this.u=null};
g.h.Pw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!C8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==C8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Bj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.UH=function(a){this.I.FC(a)};
g.h.CM=function(a){this.Pw("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.Pz=function(){var a=this.i.getOption("captions","track");g.Zb(a)||m9(this,a)};
g.h.jy=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.qk,this);var b=Math.round(a.volume);a=!!a.muted;var c=C8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.S.start();this.g.subscribe("remotePlayerChange",this.qk,this)}};
g.h.XI=function(){g.Zb(this.C)||$sa(this,this.C);this.D=!1};
g.h.yy=function(a,b){this.A.stop();2==b&&this.Oz()};
g.h.qk=function(){if(l9(this)){this.o.stop();var a=C8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.F=1;break;case 1082:case 1083:this.u.F=0;break;default:this.u.F=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.At(8));this.Nz();break;case 1085:case 3:k9(this,new g.At(9));break;case 1083:case 0:k9(this,new g.At(2));this.H.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.At(4));break;case 2:k9(this,new g.At(4));j9(this,x8(a));
break;case -1:k9(this,new g.At(64));break;case -1E3:k9(this,new g.At(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=C8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,$sa(this,a));a=C8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.S.isActive()||this.pA()}else Zsa(this)};
g.h.uy=function(){this.i.O("mdxpreviousnextchange")};
g.h.An=function(){l9(this)||Zsa(this)};
g.h.KB=function(){this.g.vu()};
g.h.Xx=function(a){a&&!g.Q(this.i.M().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Ep("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.eL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.eL=function(a,b){var c=new g.NB(this.i.M(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.oy=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.Wx=function(){this.i.O("mdxautoplaycanceled")};
g.h.pF=function(a,b){-1==C8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.pA=function(){if(l9(this)){var a=C8(this.g);this.l.Ta(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.K(this.i,"onVolumeChange",this.jy)}};
g.h.Nz=function(){this.o.stop();if(!this.g.ga()){var a=C8(this.g);1==a.playerState&&k9(this,new g.At(8));j9(this,x8(a));this.o.start()}};
g.h.Oz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(o9,g.U);o9.prototype.o=function(){B6("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.A=function(){B6("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.U);p9.prototype.u=function(a){bta(this,a.state)};g.t(q9,g.PN);q9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.C=g.ub(a,this.A,this),g.RN(this,(0,g.A)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.ke(this.A(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.A=function(a){return a.key};
q9.prototype.te=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
q9.prototype.Oc=function(a){g.PN.prototype.Oc.call(this,a);this.l.setOption("remote","currentReceiver",this.C[a]);this.o.nb()};g.t(r9,g.YO);g.h=r9.prototype;
g.h.create=function(){Tsa(g.Ty(this.player.M()));this.o.push(g.No("yt-remote-before-disconnect",this.RH,this));this.o.push(g.No("yt-remote-connection-change",this.fK,this));this.o.push(g.No("yt-remote-receiver-availability-change",this.vy,this));this.o.push(g.No("yt-remote-auto-connect",this.dK,this));this.o.push(g.No("yt-remote-receiver-resumed",this.cK,this));this.o.push(g.No("mdx-privacy-popup-confirm",this.JL,this));this.o.push(g.No("mdx-privacy-popup-cancel",this.IL,this));this.vy()};
g.h.load=function(){this.player.cancelPlayback();g.YO.prototype.load.call(this);this.u=new i9(this,this.player,this.g);var a=(a=Ysa())?a.currentTime:0;var b=e9()?new B8($8(),void 0):null;0==a&&b&&(a=x8(C8(b)));0!=a&&(this.S=a||0,this.player.O("progresssync",a,void 0));ata(this,this.C,this.C);g.gS(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Fi(this.u,this.g);this.g=this.u=null;g.YO.prototype.unload.call(this);g.gS(this.player.app,5);s9(this)};
g.h.W=function(){g.Oo(this.o);g.YO.prototype.W.call(this)};
g.h.ak=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Pw.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.F};
g.h.BC=function(){return this.loaded?this.u.suggestion:null};
g.h.Fe=function(){return this.g?C8(this.g).Fe:!1};
g.h.hasNext=function(){return this.g?C8(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.S};
g.h.getProgressState=function(){var a=C8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.M().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+v8(a):a.l,isAtLiveHead:1>=(a.u?a.i+v8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+v8(a):a.i,seekableStart:0<a.o?a.o+v8(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.cF=function(){this.g&&this.g.AA()};
g.h.RH=function(a){1==a&&(this.N=this.g?C8(this.g):null)};
g.h.fK=function(){var a=e9()?new B8($8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.N=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ei(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.N)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,x8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.vy=function(){this.H=[this.i].concat(Vsa());var a=a9()||this.i;t9(this,a);this.player.ka("onMdxReceiversChange")};
g.h.AL=function(a){!this.I&&g.mD(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.dK=function(){var a=a9();t9(this,a)};
g.h.cK=function(){this.l=a9()};
g.h.JL=function(){this.I=!0;s9(this);g9=!1;h9&&c9(h9,1);h9=null};
g.h.IL=function(){this.I=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.zc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?r8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&r8(),!0):!1}};
g.h.dF=function(){G8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ve=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.lP.remote=r9;})(_yt_player);
